joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 300
arm:
    arm_joint_controller:
        type: "position_controllers/JointTrajectoryController"
        joints: 
          - Joint_1
          - Joint_2
          - Joint_3
          - Joint_4
          - Joint_5
        gains:
            Joint_1:    {p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0}
            Joint_2:    {p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0}
            Joint_3:    {p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0}
            Joint_4:    {p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0}
            Joint_5:    {p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0}
