controller_manager_ns: controller_manager
controller_list:
    - name: arm/arm_joint_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints: 
        - arm_joint_1
        - arm_joint_2
        - arm_joint_3
        - arm_joint_4
        - arm_joint_5
