controller_list:
  - name: fake_engineer_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint7
initial:  # Define initial robot poses per group
  - group: engineer_manipulator
    pose: home